---

- name: 设置开启启动ETCD服务
  service: name=etcd enabled=yes

- name: 启动ETCD服务器
  service: name=etcd state=started

- name: 创建ETCD目录
  shell: etcdctl mkdir /kube-centos/network
  ignore_errors: yes 
  run_once: true

- name: 设置集群子网
  command: 'etcdctl mk /kube-centos/network/config ''{ "Network": "{{ cluster_cidr }}"}'''
  run_once: true
  ignore_errors: yes 

- name: 服务载入
  systemd: daemon_reload=yes name={{ item }}
  with_items:
    - docker
    - flanneld

- name: 启动服务
  systemd: name={{ item }} state=started
  with_items:
    - docker
    - flanneld
  tags: master

