
- hosts: all
  gather_facts: false
  roles:
    - k8s_common

- hosts: master
  gather_facts: false
  roles:
    - k8s_master

- hosts: node1
  gather_facts: false
  roles:
    - k8s_node1

- hosts: node2
  gather_facts: false
  roles:
    - k8s_node2

- hosts: node3
  gather_facts: false
  roles:
    - k8s_node3

- hosts: etcd
  gather_facts: false
  roles:
    - k8s_etcd

- hosts: all
  gather_facts: false
  roles:
    - k8s_common_service

- hosts: master
  gather_facts: false
  roles:
    - k8s_master_service

- hosts: nodes
  gather_facts: false
  roles:
    - k8s_nodes_service

